log4j.rootLogger=WARN, stdout
log4j.logger.fractdim=DEBUG
log4j.logger.fractdim.calculation=INFO

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
# log4j.appender.stdout.layout.ConversionPattern=%d{HH:mm:ss} %-5p %-25c{1} :: %m%n
log4j.appender.stdout.layout.ConversionPattern=%m%n
log4j.appender.stdout.threshold=INFO

log4j.appender.logfile=org.apache.log4j.FileAppender
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
# log4j.appender.logfile.layout.ConversionPattern=%d{HH:mm:ss} %-5p %-25c{1} :: %m%n
log4j.appender.logfile.layout.ConversionPattern=%m%n
log4j.appender.logfile.file=/var/log/daniel/imagetiler.log
log4j.appender.logfile.threshold=DEBUG
